/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author bug
 */
public class WithdrawFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form WithdrawFrame
     */
    public WithdrawFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hundredfifty = new javax.swing.JButton();
        twohundred = new javax.swing.JButton();
        other = new javax.swing.JButton();
        twohundredfifty = new javax.swing.JButton();
        hundred = new javax.swing.JButton();
        fifty = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(824, 615));
        setMinimumSize(new java.awt.Dimension(824, 615));

        jPanel1.setBackground(java.awt.Color.white);

        hundredfifty.setText("150$");
        hundredfifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hundredfiftyActionPerformed(evt);
            }
        });

        twohundred.setText("200$");
        twohundred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredActionPerformed(evt);
            }
        });

        other.setText("Other");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        twohundredfifty.setText("250$");
        twohundredfifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twohundredfiftyActionPerformed(evt);
            }
        });

        hundred.setText("100$");
        hundred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hundredActionPerformed(evt);
            }
        });

        fifty.setText("50$");
        fifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyActionPerformed(evt);
            }
        });

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twohundredfifty, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twohundred, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(436, 436, 436)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hundredfifty, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hundred, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fifty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(twohundred, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(twohundredfifty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fifty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hundred, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hundredfifty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hundredfiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hundredfiftyActionPerformed
        Account chosenAccount = LoginFrame.selectedAccount;
        chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - 150);
        chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                "150$ was withdrawn"
        ));
        
        File.writeTransactions();
    }//GEN-LAST:event_hundredfiftyActionPerformed

    private void twohundredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twohundredActionPerformed
        Account chosenAccount = LoginFrame.selectedAccount;
        chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - 200);
        chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                "200$ was withdrawn"
        ));
        
        File.writeTransactions();
    }//GEN-LAST:event_twohundredActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        int value = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(null, "Please enter amount"));
        if(value > 250){
            Account chosenAccount = LoginFrame.selectedAccount;
            chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - value);
            
            chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                value + "$ was withdrawn"
        ));
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Input too low");
        }
       File.writeTransactions();
    }//GEN-LAST:event_otherActionPerformed

    private void twohundredfiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twohundredfiftyActionPerformed
        Account chosenAccount = LoginFrame.selectedAccount;
        chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - 250);
        
        chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                "250$ was withdrawn"
        ));
        
        File.writeTransactions();
    }//GEN-LAST:event_twohundredfiftyActionPerformed

    private void hundredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hundredActionPerformed
        Account chosenAccount = LoginFrame.selectedAccount;
        chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - 100);
        chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                "100$ was withdrawn"
        ));
        
        File.writeTransactions();
    }//GEN-LAST:event_hundredActionPerformed

    private void fiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyActionPerformed
        Account chosenAccount = LoginFrame.selectedAccount;
        chosenAccount.setBalance(LoginFrame.selectedAccount.getBalance() - 50);
        chosenAccount.addTransaction(new Transactions(
                chosenAccount.getId(),
                "50$ was withdrawn"
        ));
        
        File.writeTransactions();
    }//GEN-LAST:event_fiftyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OptionsFrame frame = new OptionsFrame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fifty;
    private javax.swing.JButton hundred;
    private javax.swing.JButton hundredfifty;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton other;
    private javax.swing.JButton twohundred;
    private javax.swing.JButton twohundredfifty;
    // End of variables declaration//GEN-END:variables
}
